SET MODE MySQL;

CREATE TABLE IF NOT EXISTS COLLECTION_NAME_MAPPING(
    ID BIGINT PRIMARY KEY,
    COLLECTION_TYPE VARCHAR(255),
    MAP_KEY VARCHAR(255),
    MAP_VALUE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS METADATA_INFO(
    ID BIGINT PRIMARY KEY,
    META_DATA_KEY VARCHAR(255),
    META_DATA_VALUE VARCHAR(2700),
    OBJECT_ID BIGINT
);

CREATE TABLE IF NOT EXISTS STATUS_INFO(
    ID BIGINT PRIMARY KEY,
    CHECKSUM VARCHAR(255),
    ERROR CLOB,
    FILESIZE BIGINT,
    FULL_DESTINATION_PATH VARCHAR(255),
    ORGINAL_FILE_NAME VARCHAR(255),
    ORIGINAL_FILE_PATH VARCHAR(255),
    RUN_ID VARCHAR(255),
    SOURCE_FILE_NAME VARCHAR(255),
    SOURCE_FILE_PATH VARCHAR(255),
    STATUS VARCHAR(255),
    START_TIMESTAMP TIMESTAMP,
    END_TIMESTAMP TIMESTAMP,
    UPLOAD_START_TIMESTAMP TIMESTAMP,
    UPLOAD_END_TIMESTAMP TIMESTAMP,
    TAR_START_TIMESTAMP TIMESTAMP,
    TAR_END_TIMESTAMP TIMESTAMP,
    RETRY_COUNT BIGINT
);

ALTER TABLE STATUS_INFO ADD IF NOT EXISTS TAR_START_TIMESTAMP TIMESTAMP;
ALTER TABLE STATUS_INFO ADD IF NOT EXISTS TAR_END_TIMESTAMP TIMESTAMP;

CREATE TABLE IF NOT EXISTS TASK_INFO(
    ID BIGINT PRIMARY KEY,
    OBJECT_ID BIGINT,
    TASK_NAME VARCHAR(255),
    COMPLETED VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS METADATA_MAPPING(
    ID BIGINT PRIMARY KEY,
    COLLECTION_NAME VARCHAR(255),
    COLLECTION_TYPE VARCHAR(255),
    META_DATA_KEY VARCHAR(255),
	META_DATA_VALUE VARCHAR(2700)
);

CREATE TABLE IF NOT EXISTS PERMISSION_BOOKMARK_INFO(
    ID BIGINT PRIMARY KEY,
    PATH VARCHAR(255),
    USER_ID VARCHAR(255),
    PERMISSION VARCHAR(255),
    CREATE_BOOKMARK VARCHAR(255),
    CREATED VARCHAR(255),
    ERROR VARCHAR(1000)
);

ALTER TABLE STATUS_INFO DROP PRIMARY KEY;
ALTER TABLE METADATA_INFO DROP PRIMARY KEY;
ALTER TABLE COLLECTION_NAME_MAPPING DROP PRIMARY KEY;
ALTER TABLE PERMISSION_BOOKMARK_INFO DROP PRIMARY KEY;
ALTER TABLE METADATA_MAPPING DROP PRIMARY KEY;
    
ALTER TABLE STATUS_INFO ADD PRIMARY KEY (ID);
ALTER TABLE METADATA_INFO ADD PRIMARY KEY (ID);
ALTER TABLE COLLECTION_NAME_MAPPING ADD PRIMARY KEY (ID);
ALTER TABLE PERMISSION_BOOKMARK_INFO ADD PRIMARY KEY (ID);
ALTER TABLE METADATA_MAPPING ADD PRIMARY KEY (ID);