--------------------------------------------------------------------------------
-- DOC configuration tables
-- Run this script before create_doc_config_audit_triggers.sql.
-- Notes:
--   1. This script creates the base configuration tables and audit table.
--   2. Audit indexes and the audit ACTION check constraint are included in the
--      trigger script so the two scripts can be run in order without duplicate
--      object errors.
--   3. Sample INSERT statements are included at the bottom and may be removed
--      for production deployments.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Table: DOC_CONFIG
--------------------------------------------------------------------------------
CREATE TABLE DOC_CONFIG (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_NAME          VARCHAR2(128) NOT NULL,
    SERVER_ID         VARCHAR2(128) NOT NULL,
    WORKFLOW_ID       VARCHAR2(128) NOT NULL UNIQUE,
    DME_SERVER_ID     VARCHAR2(128) NOT NULL,
    DME_SERVER_URL    VARCHAR2(128) NOT NULL,
    THREADS           NUMBER,
    ENABLED           CHAR(1) DEFAULT '1',
    CRON_EXPRESSION   VARCHAR2(64) NOT NULL,
    VERSION           NUMBER NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    RUNNING_FLAG      CHAR(1) DEFAULT '0'
);

--------------------------------------------------------------------------------
-- Table: DOC_SOURCE_CONFIG
--------------------------------------------------------------------------------
CREATE TABLE DOC_SOURCE_CONFIG (
    ID                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID                NUMBER NOT NULL REFERENCES DOC_CONFIG(ID) ON DELETE CASCADE,
    SOURCE_BASE_DIR       VARCHAR2(512) NOT NULL,
    WORK_BASE_DIR         VARCHAR2(512) NOT NULL,
    DESTINATION_BASE_DIR  VARCHAR2(512) NOT NULL,
    VERSION               NUMBER NOT NULL,
    CREATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Table: DOC_SOURCE_RULE
--------------------------------------------------------------------------------
CREATE TABLE DOC_SOURCE_RULE (
    ID                                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID                                NUMBER NOT NULL REFERENCES DOC_CONFIG(ID) ON DELETE CASCADE,
    SOURCE_BASE_DIR_FOLDERS               VARCHAR2(512),
    INCLUDE_PATTERN                       VARCHAR2(512),
    EXCLUDE_PATTERN                       VARCHAR2(512),
    METADATA_FILE                         VARCHAR2(512),
    PI_METADATA_FILE                      VARCHAR2(512),
    NOSCAN_RERUN                          CHAR(1) DEFAULT '0',
    FILE_EXIST_UNDER_BASEDIR              CHAR(1) DEFAULT '0',
    FILE_EXIST_UNDER_BASEDIR_DEPTH        NUMBER,
    LAST_MODIFIED_DAYS                    NUMBER,
    LAST_MODIFIED_UNDER_BASE_DIR          CHAR(1) DEFAULT '0',
    LAST_MODIFIED_UNDER_BASE_DIR_DEPTH    NUMBER,
    SELECTIVE_SCAN                        CHAR(1) DEFAULT '0',
    RETRY_PRIOR_RUN_FAILURES              CHAR(1) DEFAULT '0',
    AWS                                   CHAR(1) DEFAULT '0',
    VERSION                               NUMBER NOT NULL,
    CREATED_AT                            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT                            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Table: DOC_PREPROCESSING_CONFIG
--------------------------------------------------------------------------------
CREATE TABLE DOC_PREPROCESSING_CONFIG (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID            NUMBER NOT NULL REFERENCES DOC_CONFIG(ID) ON DELETE CASCADE,
    TAR               CHAR(1) DEFAULT '0',
    DEPTH             NUMBER,
    FILE_TAR          CHAR(1) DEFAULT '0',
    UNTAR             CHAR(1) DEFAULT '0',
    COMPRESS_TAR      CHAR(1) DEFAULT '0',
    VERSION           NUMBER NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Table: DOC_PREPROCESSING_RULE
--------------------------------------------------------------------------------
CREATE TABLE DOC_PREPROCESSING_RULE (
    ID                                         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID                                     NUMBER NOT NULL REFERENCES DOC_CONFIG(ID) ON DELETE CASCADE,
    EXTRACT_METADATA                           CHAR(1) DEFAULT '0',
    EXTRACT_METADATA_EXT                       VARCHAR2(50),
    TAR_EXCLUDE_FOLDER                         VARCHAR2(512),
    TAR_CONTENTS_FILE                          CHAR(1) DEFAULT '0',
    TAR_EXCLUDED_CONTENTS_FILE                 CHAR(1) DEFAULT '0',
    TAR_FILE_EXIST                             VARCHAR2(50),
    TAR_FILE_EXIST_EXT                         VARCHAR2(50),
    TAR_FILENAME_EXCEL_EXIST                   CHAR(1) DEFAULT '0',
    TAR_IGNORE_BROKEN_LINK                     CHAR(1) DEFAULT '0',
    TAR_SKIP_NON_LEAF_FOLDER                   CHAR(1) DEFAULT '0',
    TAR_INCLUDE_PATTERN                        VARCHAR2(512),
    PROCESS_MULTIPLE_TARS                      CHAR(1) DEFAULT '0',
    MULTIPLE_TARS_FILES_COUNT                  NUMBER,
    MULTIPLE_TARS_DIR_FOLDERS                  VARCHAR2(512),
    MULTIPLE_TARS_DIR_FOLDERS_PREFIX           VARCHAR2(50),
    MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX       VARCHAR2(50),
    MULTIPLE_TARS_FILES_VALIDATION             CHAR(1) DEFAULT '0',
    MULTIPLE_TARS_BATCH_FOLDERS                CHAR(1) DEFAULT '0',
    MULTIPLE_TARS_BATCH_FOLDER_DELIMITER       VARCHAR2(50),
    MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL NUMBER,
    VERSION                                    NUMBER NOT NULL,
    CREATED_AT                                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT                                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Table: DOC_UPLOAD_CONFIG
--------------------------------------------------------------------------------
CREATE TABLE DOC_UPLOAD_CONFIG (
    ID                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID                   NUMBER NOT NULL REFERENCES DOC_CONFIG(ID) ON DELETE CASCADE,
    VERIFY_PREV_UPLOAD       CHAR(1) DEFAULT '0',
    DRY_RUN                  CHAR(1) DEFAULT '0',
    CHECKSUM                 CHAR(1) DEFAULT '1',
    CLEANUP_WORKDIR          CHAR(1) DEFAULT '1',
    CHECK_END_WORKFLOW       CHAR(1) DEFAULT '0',
    UPLOAD_MODIFIED_FILES    CHAR(1) DEFAULT '0',
    REPLACE_MODIFIED_FILES   CHAR(1) DEFAULT '0',
    METADATA_UPDATE_ONLY     CHAR(1) DEFAULT '0',
    MOVE_PROCESSED_FILES     CHAR(1) DEFAULT '0',
    FILESYSTEM_UPLOAD        CHAR(1) DEFAULT '0',
    SOFTLINK                 CHAR(1) DEFAULT '0',
    COLLECTION_SOFTLINK      CHAR(1) DEFAULT '0',
    SOFTLINK_FILE            VARCHAR2(512),
    VERSION                  NUMBER NOT NULL,
    CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Table: DOC_NOTIFICATION_CONFIG
--------------------------------------------------------------------------------
CREATE TABLE DOC_NOTIFICATION_CONFIG (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID            NUMBER NOT NULL REFERENCES DOC_CONFIG(ID) ON DELETE CASCADE,
    RECIPIENTS        VARCHAR2(256) NOT NULL,
    SEND_USER         CHAR(1) DEFAULT '0',
    ENABLED           CHAR(1) DEFAULT '1',
    VERSION           NUMBER NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Table: DOC_CONFIG_AUDIT
--------------------------------------------------------------------------------
CREATE TABLE DOC_CONFIG_AUDIT (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID            NUMBER NOT NULL,
    CONFIG_TYPE       VARCHAR2(64) NOT NULL,
    CONFIG_ID         NUMBER NOT NULL,
    ACTION            VARCHAR2(16) NOT NULL,
    OLD_VALUE         CLOB,
    NEW_VALUE         CLOB,
    ACTION_BY         VARCHAR2(128),
    ACTION_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

