--------------------------------------------------------------------------------
-- DOC configuration audit support
-- Creates optional audit indexes/constraint and triggers for all DOC config tables.
-- Audit model:
--   One audit row per changed config row.
--   OLD_VALUE and NEW_VALUE contain full-row JSON snapshots.
--   UPDATE triggers skip rows where only UPDATED_AT changed.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Optional indexes and constraint
--------------------------------------------------------------------------------

CREATE INDEX IDX_DOC_CONFIG_AUDIT_DOC_ID
ON DOC_CONFIG_AUDIT (DOC_ID);

CREATE INDEX IDX_DOC_CONFIG_AUDIT_CONFIG
ON DOC_CONFIG_AUDIT (CONFIG_TYPE, CONFIG_ID);

CREATE INDEX IDX_DOC_CONFIG_AUDIT_ACTION_AT
ON DOC_CONFIG_AUDIT (ACTION_AT);

ALTER TABLE DOC_CONFIG_AUDIT ADD CONSTRAINT CK_DOC_CONFIG_AUDIT_ACTION
CHECK (ACTION IN ('INSERT', 'UPDATE', 'DELETE'));

--------------------------------------------------------------------------------
-- Trigger: DOC_CONFIG
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_CONFIG
AFTER INSERT OR UPDATE OR DELETE ON DOC_CONFIG
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(
        SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'),
        SYS_CONTEXT('USERENV', 'SESSION_USER')
    );

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (
            DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY
        )
        VALUES (
            :NEW.ID,
            'DOC_CONFIG',
            :NEW.ID,
            'INSERT',
            NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_NAME' VALUE :NEW.DOC_NAME,
                'SERVER_ID' VALUE :NEW.SERVER_ID,
                'DME_SERVER_URL' VALUE :NEW.DME_SERVER_URL,
                'WORKFLOW_ID' VALUE :NEW.WORKFLOW_ID,
                'DME_SERVER_ID' VALUE :NEW.DME_SERVER_ID,
                'THREADS' VALUE :NEW.THREADS,
                'ENABLED' VALUE :NEW.ENABLED,
                'CRON_EXPRESSION' VALUE :NEW.CRON_EXPRESSION,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'RUNNING_FLAG' VALUE :NEW.RUNNING_FLAG
                RETURNING CLOB
            ),
            v_action_by
        );

    ELSIF UPDATING THEN
        IF NVL(:OLD.DOC_NAME, '~') <> NVL(:NEW.DOC_NAME, '~')
           OR NVL(:OLD.SERVER_ID, '~') <> NVL(:NEW.SERVER_ID, '~')
           OR NVL(:OLD.DME_SERVER_URL, '~') <> NVL(:NEW.DME_SERVER_URL, '~')
           OR NVL(:OLD.WORKFLOW_ID, '~') <> NVL(:NEW.WORKFLOW_ID, '~')
           OR NVL(:OLD.DME_SERVER_ID, '~') <> NVL(:NEW.DME_SERVER_ID, '~')
           OR NVL(:OLD.THREADS, -999999999) <> NVL(:NEW.THREADS, -999999999)
           OR NVL(:OLD.ENABLED, '~') <> NVL(:NEW.ENABLED, '~')
           OR NVL(:OLD.CRON_EXPRESSION, '~') <> NVL(:NEW.CRON_EXPRESSION, '~')
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
           OR NVL(:OLD.RUNNING_FLAG, '~') <> NVL(:NEW.RUNNING_FLAG, '~')
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (
                DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY
            )
            VALUES (
                :NEW.ID,
                'DOC_CONFIG',
                :NEW.ID,
                'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_NAME' VALUE :OLD.DOC_NAME,
                    'SERVER_ID' VALUE :OLD.SERVER_ID,
                    'DME_SERVER_URL' VALUE :OLD.DME_SERVER_URL,
                    'WORKFLOW_ID' VALUE :OLD.WORKFLOW_ID,
                    'DME_SERVER_ID' VALUE :OLD.DME_SERVER_ID,
                    'THREADS' VALUE :OLD.THREADS,
                    'ENABLED' VALUE :OLD.ENABLED,
                    'CRON_EXPRESSION' VALUE :OLD.CRON_EXPRESSION,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'RUNNING_FLAG' VALUE :OLD.RUNNING_FLAG
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_NAME' VALUE :NEW.DOC_NAME,
                    'SERVER_ID' VALUE :NEW.SERVER_ID,
                    'DME_SERVER_URL' VALUE :NEW.DME_SERVER_URL,
                    'WORKFLOW_ID' VALUE :NEW.WORKFLOW_ID,
                    'DME_SERVER_ID' VALUE :NEW.DME_SERVER_ID,
                    'THREADS' VALUE :NEW.THREADS,
                    'ENABLED' VALUE :NEW.ENABLED,
                    'CRON_EXPRESSION' VALUE :NEW.CRON_EXPRESSION,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'RUNNING_FLAG' VALUE :NEW.RUNNING_FLAG
                    RETURNING CLOB
                ),
                v_action_by
            );
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (
            DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY
        )
        VALUES (
            :OLD.ID,
            'DOC_CONFIG',
            :OLD.ID,
            'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_NAME' VALUE :OLD.DOC_NAME,
                'SERVER_ID' VALUE :OLD.SERVER_ID,
                'DME_SERVER_URL' VALUE :OLD.DME_SERVER_URL,
                'WORKFLOW_ID' VALUE :OLD.WORKFLOW_ID,
                'DME_SERVER_ID' VALUE :OLD.DME_SERVER_ID,
                'THREADS' VALUE :OLD.THREADS,
                'ENABLED' VALUE :OLD.ENABLED,
                'CRON_EXPRESSION' VALUE :OLD.CRON_EXPRESSION,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'RUNNING_FLAG' VALUE :OLD.RUNNING_FLAG
                RETURNING CLOB
            ),
            NULL,
            v_action_by
        );
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Trigger: DOC_SOURCE_CONFIG
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_SOURCE_CONFIG
AFTER INSERT OR UPDATE OR DELETE ON DOC_SOURCE_CONFIG
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (
            :NEW.DOC_ID,
            'DOC_SOURCE_CONFIG',
            :NEW.ID,
            'INSERT',
            NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_ID' VALUE :NEW.DOC_ID,
                'SOURCE_BASE_DIR' VALUE :NEW.SOURCE_BASE_DIR,
                'WORK_BASE_DIR' VALUE :NEW.WORK_BASE_DIR,
                'DESTINATION_BASE_DIR' VALUE :NEW.DESTINATION_BASE_DIR,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ),
            v_action_by
        );

    ELSIF UPDATING THEN
        IF NVL(:OLD.SOURCE_BASE_DIR, '~') <> NVL(:NEW.SOURCE_BASE_DIR, '~')
           OR NVL(:OLD.WORK_BASE_DIR, '~') <> NVL(:NEW.WORK_BASE_DIR, '~')
           OR NVL(:OLD.DESTINATION_BASE_DIR, '~') <> NVL(:NEW.DESTINATION_BASE_DIR, '~')
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
            VALUES (
                :NEW.DOC_ID,
                'DOC_SOURCE_CONFIG',
                :NEW.ID,
                'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_ID' VALUE :OLD.DOC_ID,
                    'SOURCE_BASE_DIR' VALUE :OLD.SOURCE_BASE_DIR,
                    'WORK_BASE_DIR' VALUE :OLD.WORK_BASE_DIR,
                    'DESTINATION_BASE_DIR' VALUE :OLD.DESTINATION_BASE_DIR,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_ID' VALUE :NEW.DOC_ID,
                    'SOURCE_BASE_DIR' VALUE :NEW.SOURCE_BASE_DIR,
                    'WORK_BASE_DIR' VALUE :NEW.WORK_BASE_DIR,
                    'DESTINATION_BASE_DIR' VALUE :NEW.DESTINATION_BASE_DIR,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                v_action_by
            );
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (
            :OLD.DOC_ID,
            'DOC_SOURCE_CONFIG',
            :OLD.ID,
            'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_ID' VALUE :OLD.DOC_ID,
                'SOURCE_BASE_DIR' VALUE :OLD.SOURCE_BASE_DIR,
                'WORK_BASE_DIR' VALUE :OLD.WORK_BASE_DIR,
                'DESTINATION_BASE_DIR' VALUE :OLD.DESTINATION_BASE_DIR,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ),
            NULL,
            v_action_by
        );
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Trigger: DOC_SOURCE_RULE
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_SOURCE_RULE
AFTER INSERT OR UPDATE OR DELETE ON DOC_SOURCE_RULE
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:NEW.DOC_ID, 'DOC_SOURCE_RULE', :NEW.ID, 'INSERT', NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_ID' VALUE :NEW.DOC_ID,
                'SOURCE_BASE_DIR_FOLDERS' VALUE :NEW.SOURCE_BASE_DIR_FOLDERS,
                'INCLUDE_PATTERN' VALUE :NEW.INCLUDE_PATTERN,
                'EXCLUDE_PATTERN' VALUE :NEW.EXCLUDE_PATTERN,
                'METADATA_FILE' VALUE :NEW.METADATA_FILE,
                'PI_METADATA_FILE' VALUE :NEW.PI_METADATA_FILE,
                'NOSCAN_RERUN' VALUE :NEW.NOSCAN_RERUN,
                'FILE_EXIST_UNDER_BASEDIR' VALUE :NEW.FILE_EXIST_UNDER_BASEDIR,
                'FILE_EXIST_UNDER_BASEDIR_DEPTH' VALUE :NEW.FILE_EXIST_UNDER_BASEDIR_DEPTH,
                'LAST_MODIFIED_DAYS' VALUE :NEW.LAST_MODIFIED_DAYS,
                'LAST_MODIFIED_UNDER_BASE_DIR' VALUE :NEW.LAST_MODIFIED_UNDER_BASE_DIR,
                'LAST_MODIFIED_UNDER_BASE_DIR_DEPTH' VALUE :NEW.LAST_MODIFIED_UNDER_BASE_DIR_DEPTH,
                'SELECTIVE_SCAN' VALUE :NEW.SELECTIVE_SCAN,
                'RETRY_PRIOR_RUN_FAILURES' VALUE :NEW.RETRY_PRIOR_RUN_FAILURES,
                'AWS' VALUE :NEW.AWS,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), v_action_by);

    ELSIF UPDATING THEN
        IF NVL(:OLD.SOURCE_BASE_DIR_FOLDERS, '~') <> NVL(:NEW.SOURCE_BASE_DIR_FOLDERS, '~')
           OR NVL(:OLD.INCLUDE_PATTERN, '~') <> NVL(:NEW.INCLUDE_PATTERN, '~')
           OR NVL(:OLD.EXCLUDE_PATTERN, '~') <> NVL(:NEW.EXCLUDE_PATTERN, '~')
           OR NVL(:OLD.METADATA_FILE, '~') <> NVL(:NEW.METADATA_FILE, '~')
           OR NVL(:OLD.PI_METADATA_FILE, '~') <> NVL(:NEW.PI_METADATA_FILE, '~')
           OR NVL(:OLD.NOSCAN_RERUN, '~') <> NVL(:NEW.NOSCAN_RERUN, '~')
           OR NVL(:OLD.FILE_EXIST_UNDER_BASEDIR, '~') <> NVL(:NEW.FILE_EXIST_UNDER_BASEDIR, '~')
           OR NVL(:OLD.FILE_EXIST_UNDER_BASEDIR_DEPTH, -999999999) <> NVL(:NEW.FILE_EXIST_UNDER_BASEDIR_DEPTH, -999999999)
           OR NVL(:OLD.LAST_MODIFIED_DAYS, -999999999) <> NVL(:NEW.LAST_MODIFIED_DAYS, -999999999)
           OR NVL(:OLD.LAST_MODIFIED_UNDER_BASE_DIR, '~') <> NVL(:NEW.LAST_MODIFIED_UNDER_BASE_DIR, '~')
           OR NVL(:OLD.LAST_MODIFIED_UNDER_BASE_DIR_DEPTH, -999999999) <> NVL(:NEW.LAST_MODIFIED_UNDER_BASE_DIR_DEPTH, -999999999)
           OR NVL(:OLD.SELECTIVE_SCAN, '~') <> NVL(:NEW.SELECTIVE_SCAN, '~')
           OR NVL(:OLD.RETRY_PRIOR_RUN_FAILURES, '~') <> NVL(:NEW.RETRY_PRIOR_RUN_FAILURES, '~')
           OR NVL(:OLD.AWS, '~') <> NVL(:NEW.AWS, '~')
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
            VALUES (:NEW.DOC_ID, 'DOC_SOURCE_RULE', :NEW.ID, 'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_ID' VALUE :OLD.DOC_ID,
                    'SOURCE_BASE_DIR_FOLDERS' VALUE :OLD.SOURCE_BASE_DIR_FOLDERS,
                    'INCLUDE_PATTERN' VALUE :OLD.INCLUDE_PATTERN,
                    'EXCLUDE_PATTERN' VALUE :OLD.EXCLUDE_PATTERN,
                    'METADATA_FILE' VALUE :OLD.METADATA_FILE,
                    'PI_METADATA_FILE' VALUE :OLD.PI_METADATA_FILE,
                    'NOSCAN_RERUN' VALUE :OLD.NOSCAN_RERUN,
                    'FILE_EXIST_UNDER_BASEDIR' VALUE :OLD.FILE_EXIST_UNDER_BASEDIR,
                    'FILE_EXIST_UNDER_BASEDIR_DEPTH' VALUE :OLD.FILE_EXIST_UNDER_BASEDIR_DEPTH,
                    'LAST_MODIFIED_DAYS' VALUE :OLD.LAST_MODIFIED_DAYS,
                    'LAST_MODIFIED_UNDER_BASE_DIR' VALUE :OLD.LAST_MODIFIED_UNDER_BASE_DIR,
                    'LAST_MODIFIED_UNDER_BASE_DIR_DEPTH' VALUE :OLD.LAST_MODIFIED_UNDER_BASE_DIR_DEPTH,
                    'SELECTIVE_SCAN' VALUE :OLD.SELECTIVE_SCAN,
                    'RETRY_PRIOR_RUN_FAILURES' VALUE :OLD.RETRY_PRIOR_RUN_FAILURES,
                    'AWS' VALUE :OLD.AWS,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_ID' VALUE :NEW.DOC_ID,
                    'SOURCE_BASE_DIR_FOLDERS' VALUE :NEW.SOURCE_BASE_DIR_FOLDERS,
                    'INCLUDE_PATTERN' VALUE :NEW.INCLUDE_PATTERN,
                    'EXCLUDE_PATTERN' VALUE :NEW.EXCLUDE_PATTERN,
                    'METADATA_FILE' VALUE :NEW.METADATA_FILE,
                    'PI_METADATA_FILE' VALUE :NEW.PI_METADATA_FILE,
                    'NOSCAN_RERUN' VALUE :NEW.NOSCAN_RERUN,
                    'FILE_EXIST_UNDER_BASEDIR' VALUE :NEW.FILE_EXIST_UNDER_BASEDIR,
                    'FILE_EXIST_UNDER_BASEDIR_DEPTH' VALUE :NEW.FILE_EXIST_UNDER_BASEDIR_DEPTH,
                    'LAST_MODIFIED_DAYS' VALUE :NEW.LAST_MODIFIED_DAYS,
                    'LAST_MODIFIED_UNDER_BASE_DIR' VALUE :NEW.LAST_MODIFIED_UNDER_BASE_DIR,
                    'LAST_MODIFIED_UNDER_BASE_DIR_DEPTH' VALUE :NEW.LAST_MODIFIED_UNDER_BASE_DIR_DEPTH,
                    'SELECTIVE_SCAN' VALUE :NEW.SELECTIVE_SCAN,
                    'RETRY_PRIOR_RUN_FAILURES' VALUE :NEW.RETRY_PRIOR_RUN_FAILURES,
                    'AWS' VALUE :NEW.AWS,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ), v_action_by);
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:OLD.DOC_ID, 'DOC_SOURCE_RULE', :OLD.ID, 'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_ID' VALUE :OLD.DOC_ID,
                'SOURCE_BASE_DIR_FOLDERS' VALUE :OLD.SOURCE_BASE_DIR_FOLDERS,
                'INCLUDE_PATTERN' VALUE :OLD.INCLUDE_PATTERN,
                'EXCLUDE_PATTERN' VALUE :OLD.EXCLUDE_PATTERN,
                'METADATA_FILE' VALUE :OLD.METADATA_FILE,
                'PI_METADATA_FILE' VALUE :OLD.PI_METADATA_FILE,
                'NOSCAN_RERUN' VALUE :OLD.NOSCAN_RERUN,
                'FILE_EXIST_UNDER_BASEDIR' VALUE :OLD.FILE_EXIST_UNDER_BASEDIR,
                'FILE_EXIST_UNDER_BASEDIR_DEPTH' VALUE :OLD.FILE_EXIST_UNDER_BASEDIR_DEPTH,
                'LAST_MODIFIED_DAYS' VALUE :OLD.LAST_MODIFIED_DAYS,
                'LAST_MODIFIED_UNDER_BASE_DIR' VALUE :OLD.LAST_MODIFIED_UNDER_BASE_DIR,
                'LAST_MODIFIED_UNDER_BASE_DIR_DEPTH' VALUE :OLD.LAST_MODIFIED_UNDER_BASE_DIR_DEPTH,
                'SELECTIVE_SCAN' VALUE :OLD.SELECTIVE_SCAN,
                'RETRY_PRIOR_RUN_FAILURES' VALUE :OLD.RETRY_PRIOR_RUN_FAILURES,
                'AWS' VALUE :OLD.AWS,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), NULL, v_action_by);
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Trigger: DOC_PREPROCESSING_CONFIG
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_PREPROCESSING_CONFIG
AFTER INSERT OR UPDATE OR DELETE ON DOC_PREPROCESSING_CONFIG
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:NEW.DOC_ID, 'DOC_PREPROCESSING_CONFIG', :NEW.ID, 'INSERT', NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_ID' VALUE :NEW.DOC_ID,
                'TAR' VALUE :NEW.TAR,
                'DEPTH' VALUE :NEW.DEPTH,
                'FILE_TAR' VALUE :NEW.FILE_TAR,
                'UNTAR' VALUE :NEW.UNTAR,
                'COMPRESS_TAR' VALUE :NEW.COMPRESS_TAR,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), v_action_by);

    ELSIF UPDATING THEN
        IF NVL(:OLD.TAR, '~') <> NVL(:NEW.TAR, '~')
           OR NVL(:OLD.DEPTH, -999999999) <> NVL(:NEW.DEPTH, -999999999)
           OR NVL(:OLD.FILE_TAR, '~') <> NVL(:NEW.FILE_TAR, '~')
           OR NVL(:OLD.UNTAR, '~') <> NVL(:NEW.UNTAR, '~')
           OR NVL(:OLD.COMPRESS_TAR, '~') <> NVL(:NEW.COMPRESS_TAR, '~')
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
            VALUES (:NEW.DOC_ID, 'DOC_PREPROCESSING_CONFIG', :NEW.ID, 'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_ID' VALUE :OLD.DOC_ID,
                    'TAR' VALUE :OLD.TAR,
                    'DEPTH' VALUE :OLD.DEPTH,
                    'FILE_TAR' VALUE :OLD.FILE_TAR,
                    'UNTAR' VALUE :OLD.UNTAR,
                    'COMPRESS_TAR' VALUE :OLD.COMPRESS_TAR,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_ID' VALUE :NEW.DOC_ID,
                    'TAR' VALUE :NEW.TAR,
                    'DEPTH' VALUE :NEW.DEPTH,
                    'FILE_TAR' VALUE :NEW.FILE_TAR,
                    'UNTAR' VALUE :NEW.UNTAR,
                    'COMPRESS_TAR' VALUE :NEW.COMPRESS_TAR,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ), v_action_by);
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:OLD.DOC_ID, 'DOC_PREPROCESSING_CONFIG', :OLD.ID, 'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_ID' VALUE :OLD.DOC_ID,
                'TAR' VALUE :OLD.TAR,
                'DEPTH' VALUE :OLD.DEPTH,
                'FILE_TAR' VALUE :OLD.FILE_TAR,
                'UNTAR' VALUE :OLD.UNTAR,
                'COMPRESS_TAR' VALUE :OLD.COMPRESS_TAR,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), NULL, v_action_by);
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Trigger: DOC_PREPROCESSING_RULE
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_PREPROCESSING_RULE
AFTER INSERT OR UPDATE OR DELETE ON DOC_PREPROCESSING_RULE
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:NEW.DOC_ID, 'DOC_PREPROCESSING_RULE', :NEW.ID, 'INSERT', NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_ID' VALUE :NEW.DOC_ID,
                'EXTRACT_METADATA' VALUE :NEW.EXTRACT_METADATA,
                'EXTRACT_METADATA_EXT' VALUE :NEW.EXTRACT_METADATA_EXT,
                'TAR_EXCLUDE_FOLDER' VALUE :NEW.TAR_EXCLUDE_FOLDER,
                'TAR_CONTENTS_FILE' VALUE :NEW.TAR_CONTENTS_FILE,
                'TAR_EXCLUDED_CONTENTS_FILE' VALUE :NEW.TAR_EXCLUDED_CONTENTS_FILE,
                'TAR_FILE_EXIST' VALUE :NEW.TAR_FILE_EXIST,
                'TAR_FILE_EXIST_EXT' VALUE :NEW.TAR_FILE_EXIST_EXT,
                'TAR_FILENAME_EXCEL_EXIST' VALUE :NEW.TAR_FILENAME_EXCEL_EXIST,
                'TAR_IGNORE_BROKEN_LINK' VALUE :NEW.TAR_IGNORE_BROKEN_LINK,
                'TAR_SKIP_NON_LEAF_FOLDER' VALUE :NEW.TAR_SKIP_NON_LEAF_FOLDER,
                'TAR_INCLUDE_PATTERN' VALUE :NEW.TAR_INCLUDE_PATTERN,
                'PROCESS_MULTIPLE_TARS' VALUE :NEW.PROCESS_MULTIPLE_TARS,
                'MULTIPLE_TARS_FILES_COUNT' VALUE :NEW.MULTIPLE_TARS_FILES_COUNT,
                'MULTIPLE_TARS_DIR_FOLDERS' VALUE :NEW.MULTIPLE_TARS_DIR_FOLDERS,
                'MULTIPLE_TARS_DIR_FOLDERS_PREFIX' VALUE :NEW.MULTIPLE_TARS_DIR_FOLDERS_PREFIX,
                'MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX' VALUE :NEW.MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX,
                'MULTIPLE_TARS_FILES_VALIDATION' VALUE :NEW.MULTIPLE_TARS_FILES_VALIDATION,
                'MULTIPLE_TARS_BATCH_FOLDERS' VALUE :NEW.MULTIPLE_TARS_BATCH_FOLDERS,
                'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER' VALUE :NEW.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER,
                'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL' VALUE :NEW.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), v_action_by);

    ELSIF UPDATING THEN
        IF NVL(:OLD.EXTRACT_METADATA, '~') <> NVL(:NEW.EXTRACT_METADATA, '~')
           OR NVL(:OLD.EXTRACT_METADATA_EXT, '~') <> NVL(:NEW.EXTRACT_METADATA_EXT, '~')
           OR NVL(:OLD.TAR_EXCLUDE_FOLDER, '~') <> NVL(:NEW.TAR_EXCLUDE_FOLDER, '~')
           OR NVL(:OLD.TAR_CONTENTS_FILE, '~') <> NVL(:NEW.TAR_CONTENTS_FILE, '~')
           OR NVL(:OLD.TAR_EXCLUDED_CONTENTS_FILE, '~') <> NVL(:NEW.TAR_EXCLUDED_CONTENTS_FILE, '~')
           OR NVL(:OLD.TAR_FILE_EXIST, '~') <> NVL(:NEW.TAR_FILE_EXIST, '~')
           OR NVL(:OLD.TAR_FILE_EXIST_EXT, '~') <> NVL(:NEW.TAR_FILE_EXIST_EXT, '~')
           OR NVL(:OLD.TAR_FILENAME_EXCEL_EXIST, '~') <> NVL(:NEW.TAR_FILENAME_EXCEL_EXIST, '~')
           OR NVL(:OLD.TAR_IGNORE_BROKEN_LINK, '~') <> NVL(:NEW.TAR_IGNORE_BROKEN_LINK, '~')
           OR NVL(:OLD.TAR_SKIP_NON_LEAF_FOLDER, '~') <> NVL(:NEW.TAR_SKIP_NON_LEAF_FOLDER, '~')
           OR NVL(:OLD.TAR_INCLUDE_PATTERN, '~') <> NVL(:NEW.TAR_INCLUDE_PATTERN, '~')
           OR NVL(:OLD.PROCESS_MULTIPLE_TARS, '~') <> NVL(:NEW.PROCESS_MULTIPLE_TARS, '~')
           OR NVL(:OLD.MULTIPLE_TARS_FILES_COUNT, -999999999) <> NVL(:NEW.MULTIPLE_TARS_FILES_COUNT, -999999999)
           OR NVL(:OLD.MULTIPLE_TARS_DIR_FOLDERS, '~') <> NVL(:NEW.MULTIPLE_TARS_DIR_FOLDERS, '~')
           OR NVL(:OLD.MULTIPLE_TARS_DIR_FOLDERS_PREFIX, '~') <> NVL(:NEW.MULTIPLE_TARS_DIR_FOLDERS_PREFIX, '~')
           OR NVL(:OLD.MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX, '~') <> NVL(:NEW.MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX, '~')
           OR NVL(:OLD.MULTIPLE_TARS_FILES_VALIDATION, '~') <> NVL(:NEW.MULTIPLE_TARS_FILES_VALIDATION, '~')
           OR NVL(:OLD.MULTIPLE_TARS_BATCH_FOLDERS, '~') <> NVL(:NEW.MULTIPLE_TARS_BATCH_FOLDERS, '~')
           OR NVL(:OLD.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER, '~') <> NVL(:NEW.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER, '~')
           OR NVL(:OLD.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL, -999999999) <> NVL(:NEW.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL, -999999999)
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
            VALUES (:NEW.DOC_ID, 'DOC_PREPROCESSING_RULE', :NEW.ID, 'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_ID' VALUE :OLD.DOC_ID,
                    'EXTRACT_METADATA' VALUE :OLD.EXTRACT_METADATA,
                    'EXTRACT_METADATA_EXT' VALUE :OLD.EXTRACT_METADATA_EXT,
                    'TAR_EXCLUDE_FOLDER' VALUE :OLD.TAR_EXCLUDE_FOLDER,
                    'TAR_CONTENTS_FILE' VALUE :OLD.TAR_CONTENTS_FILE,
                    'TAR_EXCLUDED_CONTENTS_FILE' VALUE :OLD.TAR_EXCLUDED_CONTENTS_FILE,
                    'TAR_FILE_EXIST' VALUE :OLD.TAR_FILE_EXIST,
                    'TAR_FILE_EXIST_EXT' VALUE :OLD.TAR_FILE_EXIST_EXT,
                    'TAR_FILENAME_EXCEL_EXIST' VALUE :OLD.TAR_FILENAME_EXCEL_EXIST,
                    'TAR_IGNORE_BROKEN_LINK' VALUE :OLD.TAR_IGNORE_BROKEN_LINK,
                    'TAR_SKIP_NON_LEAF_FOLDER' VALUE :OLD.TAR_SKIP_NON_LEAF_FOLDER,
                    'TAR_INCLUDE_PATTERN' VALUE :OLD.TAR_INCLUDE_PATTERN,
                    'PROCESS_MULTIPLE_TARS' VALUE :OLD.PROCESS_MULTIPLE_TARS,
                    'MULTIPLE_TARS_FILES_COUNT' VALUE :OLD.MULTIPLE_TARS_FILES_COUNT,
                    'MULTIPLE_TARS_DIR_FOLDERS' VALUE :OLD.MULTIPLE_TARS_DIR_FOLDERS,
                    'MULTIPLE_TARS_DIR_FOLDERS_PREFIX' VALUE :OLD.MULTIPLE_TARS_DIR_FOLDERS_PREFIX,
                    'MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX' VALUE :OLD.MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX,
                    'MULTIPLE_TARS_FILES_VALIDATION' VALUE :OLD.MULTIPLE_TARS_FILES_VALIDATION,
                    'MULTIPLE_TARS_BATCH_FOLDERS' VALUE :OLD.MULTIPLE_TARS_BATCH_FOLDERS,
                    'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER' VALUE :OLD.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER,
                    'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL' VALUE :OLD.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_ID' VALUE :NEW.DOC_ID,
                    'EXTRACT_METADATA' VALUE :NEW.EXTRACT_METADATA,
                    'EXTRACT_METADATA_EXT' VALUE :NEW.EXTRACT_METADATA_EXT,
                    'TAR_EXCLUDE_FOLDER' VALUE :NEW.TAR_EXCLUDE_FOLDER,
                    'TAR_CONTENTS_FILE' VALUE :NEW.TAR_CONTENTS_FILE,
                    'TAR_EXCLUDED_CONTENTS_FILE' VALUE :NEW.TAR_EXCLUDED_CONTENTS_FILE,
                    'TAR_FILE_EXIST' VALUE :NEW.TAR_FILE_EXIST,
                    'TAR_FILE_EXIST_EXT' VALUE :NEW.TAR_FILE_EXIST_EXT,
                    'TAR_FILENAME_EXCEL_EXIST' VALUE :NEW.TAR_FILENAME_EXCEL_EXIST,
                    'TAR_IGNORE_BROKEN_LINK' VALUE :NEW.TAR_IGNORE_BROKEN_LINK,
                    'TAR_SKIP_NON_LEAF_FOLDER' VALUE :NEW.TAR_SKIP_NON_LEAF_FOLDER,
                    'TAR_INCLUDE_PATTERN' VALUE :NEW.TAR_INCLUDE_PATTERN,
                    'PROCESS_MULTIPLE_TARS' VALUE :NEW.PROCESS_MULTIPLE_TARS,
                    'MULTIPLE_TARS_FILES_COUNT' VALUE :NEW.MULTIPLE_TARS_FILES_COUNT,
                    'MULTIPLE_TARS_DIR_FOLDERS' VALUE :NEW.MULTIPLE_TARS_DIR_FOLDERS,
                    'MULTIPLE_TARS_DIR_FOLDERS_PREFIX' VALUE :NEW.MULTIPLE_TARS_DIR_FOLDERS_PREFIX,
                    'MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX' VALUE :NEW.MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX,
                    'MULTIPLE_TARS_FILES_VALIDATION' VALUE :NEW.MULTIPLE_TARS_FILES_VALIDATION,
                    'MULTIPLE_TARS_BATCH_FOLDERS' VALUE :NEW.MULTIPLE_TARS_BATCH_FOLDERS,
                    'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER' VALUE :NEW.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER,
                    'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL' VALUE :NEW.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ), v_action_by);
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:OLD.DOC_ID, 'DOC_PREPROCESSING_RULE', :OLD.ID, 'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_ID' VALUE :OLD.DOC_ID,
                'EXTRACT_METADATA' VALUE :OLD.EXTRACT_METADATA,
                'EXTRACT_METADATA_EXT' VALUE :OLD.EXTRACT_METADATA_EXT,
                'TAR_EXCLUDE_FOLDER' VALUE :OLD.TAR_EXCLUDE_FOLDER,
                'TAR_CONTENTS_FILE' VALUE :OLD.TAR_CONTENTS_FILE,
                'TAR_EXCLUDED_CONTENTS_FILE' VALUE :OLD.TAR_EXCLUDED_CONTENTS_FILE,
                'TAR_FILE_EXIST' VALUE :OLD.TAR_FILE_EXIST,
                'TAR_FILE_EXIST_EXT' VALUE :OLD.TAR_FILE_EXIST_EXT,
                'TAR_FILENAME_EXCEL_EXIST' VALUE :OLD.TAR_FILENAME_EXCEL_EXIST,
                'TAR_IGNORE_BROKEN_LINK' VALUE :OLD.TAR_IGNORE_BROKEN_LINK,
                'TAR_SKIP_NON_LEAF_FOLDER' VALUE :OLD.TAR_SKIP_NON_LEAF_FOLDER,
                'TAR_INCLUDE_PATTERN' VALUE :OLD.TAR_INCLUDE_PATTERN,
                'PROCESS_MULTIPLE_TARS' VALUE :OLD.PROCESS_MULTIPLE_TARS,
                'MULTIPLE_TARS_FILES_COUNT' VALUE :OLD.MULTIPLE_TARS_FILES_COUNT,
                'MULTIPLE_TARS_DIR_FOLDERS' VALUE :OLD.MULTIPLE_TARS_DIR_FOLDERS,
                'MULTIPLE_TARS_DIR_FOLDERS_PREFIX' VALUE :OLD.MULTIPLE_TARS_DIR_FOLDERS_PREFIX,
                'MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX' VALUE :OLD.MULTIPLE_TARS_EXCLUDE_FOLDERS_PREFIX,
                'MULTIPLE_TARS_FILES_VALIDATION' VALUE :OLD.MULTIPLE_TARS_FILES_VALIDATION,
                'MULTIPLE_TARS_BATCH_FOLDERS' VALUE :OLD.MULTIPLE_TARS_BATCH_FOLDERS,
                'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER' VALUE :OLD.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER,
                'MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL' VALUE :OLD.MULTIPLE_TARS_BATCH_FOLDER_DELIMITER_LEVEL,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), NULL, v_action_by);
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Trigger: DOC_UPLOAD_CONFIG
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_UPLOAD_CONFIG
AFTER INSERT OR UPDATE OR DELETE ON DOC_UPLOAD_CONFIG
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:NEW.DOC_ID, 'DOC_UPLOAD_CONFIG', :NEW.ID, 'INSERT', NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_ID' VALUE :NEW.DOC_ID,
                'VERIFY_PREV_UPLOAD' VALUE :NEW.VERIFY_PREV_UPLOAD,
                'DRY_RUN' VALUE :NEW.DRY_RUN,
                'CHECKSUM' VALUE :NEW.CHECKSUM,
                'CLEANUP_WORKDIR' VALUE :NEW.CLEANUP_WORKDIR,
                'CHECK_END_WORKFLOW' VALUE :NEW.CHECK_END_WORKFLOW,
                'UPLOAD_MODIFIED_FILES' VALUE :NEW.UPLOAD_MODIFIED_FILES,
                'REPLACE_MODIFIED_FILES' VALUE :NEW.REPLACE_MODIFIED_FILES,
                'METADATA_UPDATE_ONLY' VALUE :NEW.METADATA_UPDATE_ONLY,
                'MOVE_PROCESSED_FILES' VALUE :NEW.MOVE_PROCESSED_FILES,
                'FILESYSTEM_UPLOAD' VALUE :NEW.FILESYSTEM_UPLOAD,
                'SOFTLINK' VALUE :NEW.SOFTLINK,
                'COLLECTION_SOFTLINK' VALUE :NEW.COLLECTION_SOFTLINK,
                'SOFTLINK_FILE' VALUE :NEW.SOFTLINK_FILE,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), v_action_by);

    ELSIF UPDATING THEN
        IF NVL(:OLD.VERIFY_PREV_UPLOAD, '~') <> NVL(:NEW.VERIFY_PREV_UPLOAD, '~')
           OR NVL(:OLD.DRY_RUN, '~') <> NVL(:NEW.DRY_RUN, '~')
           OR NVL(:OLD.CHECKSUM, '~') <> NVL(:NEW.CHECKSUM, '~')
           OR NVL(:OLD.CLEANUP_WORKDIR, '~') <> NVL(:NEW.CLEANUP_WORKDIR, '~')
           OR NVL(:OLD.CHECK_END_WORKFLOW, '~') <> NVL(:NEW.CHECK_END_WORKFLOW, '~')
           OR NVL(:OLD.UPLOAD_MODIFIED_FILES, '~') <> NVL(:NEW.UPLOAD_MODIFIED_FILES, '~')
           OR NVL(:OLD.REPLACE_MODIFIED_FILES, '~') <> NVL(:NEW.REPLACE_MODIFIED_FILES, '~')
           OR NVL(:OLD.METADATA_UPDATE_ONLY, '~') <> NVL(:NEW.METADATA_UPDATE_ONLY, '~')
           OR NVL(:OLD.MOVE_PROCESSED_FILES, '~') <> NVL(:NEW.MOVE_PROCESSED_FILES, '~')
           OR NVL(:OLD.FILESYSTEM_UPLOAD, '~') <> NVL(:NEW.FILESYSTEM_UPLOAD, '~')
           OR NVL(:OLD.SOFTLINK, '~') <> NVL(:NEW.SOFTLINK, '~')
           OR NVL(:OLD.COLLECTION_SOFTLINK, '~') <> NVL(:NEW.COLLECTION_SOFTLINK, '~')
           OR NVL(:OLD.SOFTLINK_FILE, '~') <> NVL(:NEW.SOFTLINK_FILE, '~')
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
            VALUES (:NEW.DOC_ID, 'DOC_UPLOAD_CONFIG', :NEW.ID, 'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_ID' VALUE :OLD.DOC_ID,
                    'VERIFY_PREV_UPLOAD' VALUE :OLD.VERIFY_PREV_UPLOAD,
                    'DRY_RUN' VALUE :OLD.DRY_RUN,
                    'CHECKSUM' VALUE :OLD.CHECKSUM,
                    'CLEANUP_WORKDIR' VALUE :OLD.CLEANUP_WORKDIR,
                    'CHECK_END_WORKFLOW' VALUE :OLD.CHECK_END_WORKFLOW,
                    'UPLOAD_MODIFIED_FILES' VALUE :OLD.UPLOAD_MODIFIED_FILES,
                    'REPLACE_MODIFIED_FILES' VALUE :OLD.REPLACE_MODIFIED_FILES,
                    'METADATA_UPDATE_ONLY' VALUE :OLD.METADATA_UPDATE_ONLY,
                    'MOVE_PROCESSED_FILES' VALUE :OLD.MOVE_PROCESSED_FILES,
                    'FILESYSTEM_UPLOAD' VALUE :OLD.FILESYSTEM_UPLOAD,
                    'SOFTLINK' VALUE :OLD.SOFTLINK,
                    'COLLECTION_SOFTLINK' VALUE :OLD.COLLECTION_SOFTLINK,
                    'SOFTLINK_FILE' VALUE :OLD.SOFTLINK_FILE,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_ID' VALUE :NEW.DOC_ID,
                    'VERIFY_PREV_UPLOAD' VALUE :NEW.VERIFY_PREV_UPLOAD,
                    'DRY_RUN' VALUE :NEW.DRY_RUN,
                    'CHECKSUM' VALUE :NEW.CHECKSUM,
                    'CLEANUP_WORKDIR' VALUE :NEW.CLEANUP_WORKDIR,
                    'CHECK_END_WORKFLOW' VALUE :NEW.CHECK_END_WORKFLOW,
                    'UPLOAD_MODIFIED_FILES' VALUE :NEW.UPLOAD_MODIFIED_FILES,
                    'REPLACE_MODIFIED_FILES' VALUE :NEW.REPLACE_MODIFIED_FILES,
                    'METADATA_UPDATE_ONLY' VALUE :NEW.METADATA_UPDATE_ONLY,
                    'MOVE_PROCESSED_FILES' VALUE :NEW.MOVE_PROCESSED_FILES,
                    'FILESYSTEM_UPLOAD' VALUE :NEW.FILESYSTEM_UPLOAD,
                    'SOFTLINK' VALUE :NEW.SOFTLINK,
                    'COLLECTION_SOFTLINK' VALUE :NEW.COLLECTION_SOFTLINK,
                    'SOFTLINK_FILE' VALUE :NEW.SOFTLINK_FILE,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ), v_action_by);
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:OLD.DOC_ID, 'DOC_UPLOAD_CONFIG', :OLD.ID, 'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_ID' VALUE :OLD.DOC_ID,
                'VERIFY_PREV_UPLOAD' VALUE :OLD.VERIFY_PREV_UPLOAD,
                'DRY_RUN' VALUE :OLD.DRY_RUN,
                'CHECKSUM' VALUE :OLD.CHECKSUM,
                'CLEANUP_WORKDIR' VALUE :OLD.CLEANUP_WORKDIR,
                'CHECK_END_WORKFLOW' VALUE :OLD.CHECK_END_WORKFLOW,
                'UPLOAD_MODIFIED_FILES' VALUE :OLD.UPLOAD_MODIFIED_FILES,
                'REPLACE_MODIFIED_FILES' VALUE :OLD.REPLACE_MODIFIED_FILES,
                'METADATA_UPDATE_ONLY' VALUE :OLD.METADATA_UPDATE_ONLY,
                'MOVE_PROCESSED_FILES' VALUE :OLD.MOVE_PROCESSED_FILES,
                'FILESYSTEM_UPLOAD' VALUE :OLD.FILESYSTEM_UPLOAD,
                'SOFTLINK' VALUE :OLD.SOFTLINK,
                'COLLECTION_SOFTLINK' VALUE :OLD.COLLECTION_SOFTLINK,
                'SOFTLINK_FILE' VALUE :OLD.SOFTLINK_FILE,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), NULL, v_action_by);
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Trigger: DOC_NOTIFICATION_CONFIG
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_DOC_NOTIFICATION_CONFIG
AFTER INSERT OR UPDATE OR DELETE ON DOC_NOTIFICATION_CONFIG
FOR EACH ROW
DECLARE
    v_action_by VARCHAR2(128);
BEGIN
    v_action_by := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF INSERTING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:NEW.DOC_ID, 'DOC_NOTIFICATION_CONFIG', :NEW.ID, 'INSERT', NULL,
            JSON_OBJECT(
                'ID' VALUE :NEW.ID,
                'DOC_ID' VALUE :NEW.DOC_ID,
                'RECIPIENTS' VALUE :NEW.RECIPIENTS,
                'SEND_USER' VALUE :NEW.SEND_USER,
                'ENABLED' VALUE :NEW.ENABLED,
                'VERSION' VALUE :NEW.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), v_action_by);

    ELSIF UPDATING THEN
        IF NVL(:OLD.RECIPIENTS, '~') <> NVL(:NEW.RECIPIENTS, '~')
           OR NVL(:OLD.SEND_USER, '~') <> NVL(:NEW.SEND_USER, '~')
           OR NVL(:OLD.ENABLED, '~') <> NVL(:NEW.ENABLED, '~')
           OR NVL(:OLD.VERSION, -999999999) <> NVL(:NEW.VERSION, -999999999)
        THEN
            INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
            VALUES (:NEW.DOC_ID, 'DOC_NOTIFICATION_CONFIG', :NEW.ID, 'UPDATE',
                JSON_OBJECT(
                    'ID' VALUE :OLD.ID,
                    'DOC_ID' VALUE :OLD.DOC_ID,
                    'RECIPIENTS' VALUE :OLD.RECIPIENTS,
                    'SEND_USER' VALUE :OLD.SEND_USER,
                    'ENABLED' VALUE :OLD.ENABLED,
                    'VERSION' VALUE :OLD.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ),
                JSON_OBJECT(
                    'ID' VALUE :NEW.ID,
                    'DOC_ID' VALUE :NEW.DOC_ID,
                    'RECIPIENTS' VALUE :NEW.RECIPIENTS,
                    'SEND_USER' VALUE :NEW.SEND_USER,
                    'ENABLED' VALUE :NEW.ENABLED,
                    'VERSION' VALUE :NEW.VERSION,
                    'CREATED_AT' VALUE TO_CHAR(:NEW.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                    'UPDATED_AT' VALUE TO_CHAR(:NEW.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                    RETURNING CLOB
                ), v_action_by);
        END IF;

    ELSIF DELETING THEN
        INSERT INTO DOC_CONFIG_AUDIT (DOC_ID, CONFIG_TYPE, CONFIG_ID, ACTION, OLD_VALUE, NEW_VALUE, ACTION_BY)
        VALUES (:OLD.DOC_ID, 'DOC_NOTIFICATION_CONFIG', :OLD.ID, 'DELETE',
            JSON_OBJECT(
                'ID' VALUE :OLD.ID,
                'DOC_ID' VALUE :OLD.DOC_ID,
                'RECIPIENTS' VALUE :OLD.RECIPIENTS,
                'SEND_USER' VALUE :OLD.SEND_USER,
                'ENABLED' VALUE :OLD.ENABLED,
                'VERSION' VALUE :OLD.VERSION,
                'CREATED_AT' VALUE TO_CHAR(:OLD.CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF'),
                'UPDATED_AT' VALUE TO_CHAR(:OLD.UPDATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
                RETURNING CLOB
            ), NULL, v_action_by);
    END IF;
END;
/

