name: Test the runner
permissions:
  contents: write
  id-token: write
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Run your steps
        run: echo "Using the org-level runner!"
